services:
  db:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./payload-next-js-cms/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data:
  # pgdata:
  node_modules:
